### ISSUE TITLE
"Avoid secondary industry stealing" causes the AI to crash

### ISSUE THREAD

**Issue by bigyihsuan** [rei-artist/AAAHogEx#1]
I reported it [in the forum thread][1] already, but I'll post it here:

The "Avoid secondary industry stealing" setting causes the AI to crash, reporting a `"AddNgPlace" does not exist` error in AAAHogEx v29. Turning the setting off stops the crash.

![image](https://user-images.githubusercontent.com/12767476/223829687-b31411b5-2df8-489b-aa87-a9607dd09e64.png)

https://github.com/rei-artist/AAAHogEx/blob/57403b772694a88d0ec011d309122d8a15830925/place.nut#L558

What's strange is that the function is already defined in the same file:

https://github.com/rei-artist/AAAHogEx/blob/57403b772694a88d0ec011d309122d8a15830925/place.nut#L524-L530

[1]: https://www.tt-forums.net/viewtopic.php?p=1258999#p1258999

**Comment by rei-artist** [comment]
Fixed in v30
