### ISSUE TITLE
Zero cost eyecandy cars crash AAAHogEx when it tries to build a passenger route

### ISSUE THREAD

**Issue by James103** [rei-artist/AAAHogEx#2]
I was running AAAHogEx along with CityLife AI using eyecandy road vehicles NewGRFs (Eyecandy Road Vehicles, Funny Cars, Generic Cars, and DROP) when AAAHogEx v89 crashed with a divide by zero error here: https://github.com/rei-artist/AAAHogEx/blob/1b657db0552133b1f816a64293ca79ae673fa499/route.nut#L2821

![image](https://github.com/rei-artist/AAAHogEx/assets/37945304/005e311b-943a-49c7-ba91-7a3b3d5b76e8)

Configuration:
![image](https://github.com/rei-artist/AAAHogEx/assets/37945304/2a858e52-8f03-41bd-a2aa-581b201fb18c)

**Comment by rei-artist** [comment]
v90
